#!/bin/sh

echo "Cleanup...";
rm -fr bower_components/
echo "Downloading..."
bower install bootstrap markdown-js chartist angular-route angular-translate-loader-static-files angular-translate-storage-cookie angular-translate-storage-local angular-websocket angular-sanitize --allow-root
echo "Removing old files..."
rm -fr app/static/lib/*
echo "Creating dirs..."
mkdir app/static/lib/jquery/
mkdir app/static/lib/bootstrap/
mkdir app/static/lib/fonts/
mkdir -p app/static/lib/angularjs/plugins/angular-route/
mkdir app/static/lib/angularjs/plugins/angular-sanitize/
mkdir app/static/lib/angularjs/plugins/angular-translate/
mkdir app/static/lib/angularjs/plugins/angular-cookies/
mkdir app/static/lib/angularjs/plugins/angular-websocket/
mkdir app/static/lib/chartist/
mkdir app/static/lib/markdown-js/
echo "Copying files into static/lib..."
# angular
cp bower_components/angular/angular.js app/static/lib/angularjs/
# angular-route
cp bower_components/angular-route/angular-route.js app/static/lib/angularjs/plugins/angular-route/
# angular-sanitize
cp bower_components/angular-sanitize/angular-sanitize.js app/static/lib/angularjs/plugins/angular-sanitize/
# angular-translate
cp bower_components/angular-translate/angular-translate.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-cookies/angular-cookies.js app/static/lib/angularjs/plugins/angular-cookies/
cp bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-translate-storage-local/angular-translate-storage-local.js app/static/lib/angularjs/plugins/angular-translate/
# angular-websocket
cp bower_components/angular-websocket/angular-websocket.js app/static/lib/angularjs/plugins/angular-websocket/
# bootstrap
cp bower_components/bootstrap/dist/css/bootstrap-theme.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/css/bootstrap.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/js/bootstrap.js app/static/lib/bootstrap/
cp -R bower_components/bootstrap/fonts/ app/static/lib/fonts/
# jquery
cp bower_components/jquery/dist/jquery.js app/static/lib/jquery/
# chartist
cp bower_components/chartist/dist/chartist.min.css app/static/lib/chartist/
cp bower_components/chartist/dist/chartist.js app/static/lib/chartist/
# markdown-js
cp bower_components/markdown-js/dist/markdown.js app/static/lib/markdown-js

echo "Removing bower_components/..."
rm -fr bower_components/
echo "done."
