#!/bin/bash

echo "Cleanup...";
rm -fr bower_components/
echo "Downloading..."
bower install bootstrap angular-route angular-translate-loader-static-files angular-translate-storage-cookie angular-translate-storage-local chartist angular-websocket --allow-root
echo "Removing old files..."
rm -fr app/static/lib/*
echo "Creating dirs..."
mkdir app/static/lib/jquery
mkdir app/static/lib/bootstrap
mkdir app/static/lib/fonts
mkdir -p app/static/lib/angularjs/plugins/angular-route
mkdir app/static/lib/angularjs/plugins/angular-translate
mkdir app/static/lib/angularjs/plugins/angular-cookies/
mkdir app/static/lib/angularjs/plugins/angular-websocket/
mkdir app/static/lib/chartist
echo "Copying files into static/lib..."
# angular
cp bower_components/angular/angular.min.js app/static/lib/angularjs/
# angular-route
cp bower_components/angular-route/angular-route.min.js app/static/lib/angularjs/plugins/angular-route/
# angular-translate
cp bower_components/angular-translate/angular-translate.min.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-cookies/angular-cookies.min.js app/static/lib/angularjs/plugins/angular-cookies/
cp bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-translate-storage-local/angular-translate-storage-local.min.js app/static/lib/angularjs/plugins/angular-translate/
# angular-websocket
cp bower_components/angular-websocket/angular-websocket.min.js app/static/lib/angularjs/plugins/angular-websocket/
# bootstrap
cp bower_components/bootstrap/dist/css/bootstrap-theme.min.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/css/bootstrap.min.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/js/bootstrap.min.js app/static/lib/bootstrap/
cp -R bower_components/bootstrap/fonts/ app/static/lib/fonts/
# jquery
cp bower_components/jquery/dist/jquery.min.js app/static/lib/jquery/
# chartist
cp bower_components/chartist/dist/chartist.min.css app/static/lib/chartist/
cp bower_components/chartist/dist/chartist.min.js app/static/lib/chartist/

echo "Removing bower_components/..."
rm -fr bower_components/
echo "done."
